name: 05 - ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 09-ci-cd

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: lint del Frontend
        run: |
          pnpm lint:frontend

  frontend-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 09-ci-cd

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Tests del Frontend
        run: pnpm test:frontend

  frontend-build:
    needs: [frontend-lint, frontend-test]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Build del Frontend
        run: pnpm build:frontend

  backend-lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 09-ci-cd

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: backend lint
        run: pnpm lint:backend

  backend-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 09-ci-cd

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: backend test
        run: pnpm test:backend

  backend-smoke-test:
    needs: [backend-lint, backend-test]
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 09-ci-cd/backend
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: backend smoke test
        run: |
          pnpm build:backend
          pnpm run dev:backend
          curl -X GET http://localhost:1234/health
