name: 05 - ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: 09-ci-cd

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: Preparar pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: Instalar dependencias
        run: |
          pnpm install --config.ignore-scripts=true
          echo 'Hola'

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "09-ci-cd/Backend/pnpm-lock.yaml"

      - name: instalar dependencias de IA
        run: |
          pnpm add openai
          pnpm add @google/genai

      - name: Crear variables de entorno dummy
        working-directory: ./09-ci-cd/Backend
        run: touch .env

      - name: Lanzar test
        run: |
          cd Backend
          pnpm run test
