name: 05 - ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-lint:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: 09-ci-cd

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/action.yml
      - name: lint del Frontend
        run: |
          pnpm lint:frontend

  frontend-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/action.yml
      - name: Tests del Frontend
        run: pnpm test:frontend

  backend-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/action.yml
      - name: backend lint
        run: pnpm lint:backend

  backend-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/action.yml
      - name: backend test
        run: pnpm test:backend
